### ISSUE TITLE
Publishing of the package

### ISSUE THREAD

**Issue by lauhon** [ExodusMovement/react-native-wasm#2]
Is this package actually published and in a stable state?

On npmjs.com I can only find [this react-native-wasm package](https://www.npmjs.com/package/react-native-wasm) which doesn't seem to be this one.

**Comment by mvayngrib** [comment]
this is an abandoned experiment, i'm going to update the project description

**Comment by lauhon** [comment]
Aye, thanks for the information. Often people don't take the time to answer on abandoned projects, so I appreciate it ^^

Any idea if there is something similar that is still alive?
